/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ClientProfile {
  'city' : string,
  'neighborhood' : string,
  'name' : string,
  'profilePhotoId' : string,
  'phone' : string,
}
export interface JobCompletionRecord {
  'client' : Principal,
  'rating' : number,
  'worker' : Principal,
}
export interface JobListing {
  'title' : string,
  'urgency' : boolean,
  'hourlyRate' : [] | [bigint],
  'profession' : string,
  'description' : string,
  'isVerified' : boolean,
  'category' : string,
  'budget' : bigint,
  'requiredSkills' : Array<string>,
  'location' : string,
}
export interface UserProfile {
  'userType' : { 'client' : null } |
    { 'company' : null } |
    { 'worker' : null },
  'city' : string,
  'neighborhood' : string,
  'name' : string,
  'profilePhotoId' : string,
  'hourlyRate' : [] | [bigint],
  'profession' : [] | [string],
  'isAvailable' : [] | [boolean],
  'trustBadges' : Array<string>,
  'experienceYears' : [] | [bigint],
  'rating' : [] | [number],
  'phone' : string,
  'jobCount' : [] | [bigint],
  'skills' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkerProfile {
  'city' : string,
  'neighborhood' : string,
  'name' : string,
  'profilePhotoId' : string,
  'hourlyRate' : bigint,
  'profession' : string,
  'isAvailable' : boolean,
  'trustBadges' : Array<string>,
  'experienceYears' : bigint,
  'rating' : number,
  'phone' : string,
  'jobCount' : bigint,
  'skills' : Array<string>,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'addJobCompletionRecord' : ActorMethod<[Principal, number], undefined>,
  'addJobListing' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      string,
      bigint,
      boolean,
      string,
      string,
      [] | [bigint],
    ],
    undefined
  >,
  'addWorker' : ActorMethod<
    [string, string, string, string, string, string, bigint],
    undefined
  >,
  'addWorkerSkill' : ActorMethod<[string], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllClients' : ActorMethod<[], Array<[Principal, ClientProfile]>>,
  'getAllJobListings' : ActorMethod<[], Array<[Principal, JobListing]>>,
  'getAllWorkers' : ActorMethod<[], Array<[Principal, WorkerProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientProfile' : ActorMethod<[Principal], [] | [ClientProfile]>,
  'getJobCompletionRecords' : ActorMethod<[], Array<JobCompletionRecord>>,
  'getJobListing' : ActorMethod<[Principal], [] | [JobListing]>,
  'getMyClientProfile' : ActorMethod<[], [] | [ClientProfile]>,
  'getMyJobListings' : ActorMethod<[], Array<JobListing>>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerProfile' : ActorMethod<[Principal], [] | [WorkerProfile]>,
  'getWorkerRatings' : ActorMethod<[Principal], Array<JobCompletionRecord>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateWorkerAvailability' : ActorMethod<[boolean], boolean>,
  'verifyJobListing' : ActorMethod<[Principal], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];