/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientProfile = IDL.Record({
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'profilePhotoId' : IDL.Text,
  'phone' : IDL.Text,
});
export const JobListing = IDL.Record({
  'title' : IDL.Text,
  'urgency' : IDL.Bool,
  'hourlyRate' : IDL.Opt(IDL.Nat),
  'profession' : IDL.Text,
  'description' : IDL.Text,
  'isVerified' : IDL.Bool,
  'category' : IDL.Text,
  'budget' : IDL.Nat,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const WorkerProfile = IDL.Record({
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'profilePhotoId' : IDL.Text,
  'hourlyRate' : IDL.Nat,
  'profession' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'trustBadges' : IDL.Vec(IDL.Text),
  'experienceYears' : IDL.Nat,
  'rating' : IDL.Float64,
  'phone' : IDL.Text,
  'jobCount' : IDL.Nat,
  'skills' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Variant({
    'client' : IDL.Null,
    'company' : IDL.Null,
    'worker' : IDL.Null,
  }),
  'city' : IDL.Text,
  'neighborhood' : IDL.Text,
  'name' : IDL.Text,
  'profilePhotoId' : IDL.Text,
  'hourlyRate' : IDL.Opt(IDL.Nat),
  'profession' : IDL.Opt(IDL.Text),
  'isAvailable' : IDL.Opt(IDL.Bool),
  'trustBadges' : IDL.Vec(IDL.Text),
  'experienceYears' : IDL.Opt(IDL.Nat),
  'rating' : IDL.Opt(IDL.Float64),
  'phone' : IDL.Text,
  'jobCount' : IDL.Opt(IDL.Nat),
  'skills' : IDL.Vec(IDL.Text),
});
export const JobCompletionRecord = IDL.Record({
  'client' : IDL.Principal,
  'rating' : IDL.Float64,
  'worker' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addJobCompletionRecord' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
  'addJobListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Nat),
      ],
      [],
      [],
    ),
  'addWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'addWorkerSkill' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllClients' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, ClientProfile))],
      ['query'],
    ),
  'getAllJobListings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, JobListing))],
      ['query'],
    ),
  'getAllWorkers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, WorkerProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ClientProfile)],
      ['query'],
    ),
  'getJobCompletionRecords' : IDL.Func(
      [],
      [IDL.Vec(JobCompletionRecord)],
      ['query'],
    ),
  'getJobListing' : IDL.Func([IDL.Principal], [IDL.Opt(JobListing)], ['query']),
  'getMyClientProfile' : IDL.Func([], [IDL.Opt(ClientProfile)], ['query']),
  'getMyJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
  'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'getWorkerRatings' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobCompletionRecord)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateWorkerAvailability' : IDL.Func([IDL.Bool], [IDL.Bool], []),
  'verifyJobListing' : IDL.Func([IDL.Principal], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientProfile = IDL.Record({
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'profilePhotoId' : IDL.Text,
    'phone' : IDL.Text,
  });
  const JobListing = IDL.Record({
    'title' : IDL.Text,
    'urgency' : IDL.Bool,
    'hourlyRate' : IDL.Opt(IDL.Nat),
    'profession' : IDL.Text,
    'description' : IDL.Text,
    'isVerified' : IDL.Bool,
    'category' : IDL.Text,
    'budget' : IDL.Nat,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const WorkerProfile = IDL.Record({
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'profilePhotoId' : IDL.Text,
    'hourlyRate' : IDL.Nat,
    'profession' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'trustBadges' : IDL.Vec(IDL.Text),
    'experienceYears' : IDL.Nat,
    'rating' : IDL.Float64,
    'phone' : IDL.Text,
    'jobCount' : IDL.Nat,
    'skills' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Variant({
      'client' : IDL.Null,
      'company' : IDL.Null,
      'worker' : IDL.Null,
    }),
    'city' : IDL.Text,
    'neighborhood' : IDL.Text,
    'name' : IDL.Text,
    'profilePhotoId' : IDL.Text,
    'hourlyRate' : IDL.Opt(IDL.Nat),
    'profession' : IDL.Opt(IDL.Text),
    'isAvailable' : IDL.Opt(IDL.Bool),
    'trustBadges' : IDL.Vec(IDL.Text),
    'experienceYears' : IDL.Opt(IDL.Nat),
    'rating' : IDL.Opt(IDL.Float64),
    'phone' : IDL.Text,
    'jobCount' : IDL.Opt(IDL.Nat),
    'skills' : IDL.Vec(IDL.Text),
  });
  const JobCompletionRecord = IDL.Record({
    'client' : IDL.Principal,
    'rating' : IDL.Float64,
    'worker' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addJobCompletionRecord' : IDL.Func([IDL.Principal, IDL.Float64], [], []),
    'addJobListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Nat),
        ],
        [],
        [],
      ),
    'addWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'addWorkerSkill' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllClients' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, ClientProfile))],
        ['query'],
      ),
    'getAllJobListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, JobListing))],
        ['query'],
      ),
    'getAllWorkers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, WorkerProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ClientProfile)],
        ['query'],
      ),
    'getJobCompletionRecords' : IDL.Func(
        [],
        [IDL.Vec(JobCompletionRecord)],
        ['query'],
      ),
    'getJobListing' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(JobListing)],
        ['query'],
      ),
    'getMyClientProfile' : IDL.Func([], [IDL.Opt(ClientProfile)], ['query']),
    'getMyJobListings' : IDL.Func([], [IDL.Vec(JobListing)], ['query']),
    'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'getWorkerRatings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobCompletionRecord)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateWorkerAvailability' : IDL.Func([IDL.Bool], [IDL.Bool], []),
    'verifyJobListing' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };